### ISSUE TITLE
Permission denied problem with nbconvert

### ISSUE THREAD

**Issue by gideonsimpson** [jupyter/nbconvert#1430]
I have a conda installation of jupyter and, after a recent update, my ability to export and otherwise convert jupyter notebooks has been curtailed.  For instance, I'm having the following problem at the command line:

```
guardian@titan:scratch$ jupyter nbconvert --to html mynotebook.ipynb 
Traceback (most recent call last):
  File "/Users/guardian/miniconda3/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 140, in <module>
    class NbConvertApp(JupyterApp):
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 225, in NbConvertApp
    """.format(formats=get_export_names()))
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
    if getattr(exporter(config=config), 'enabled', True):
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 328, in __init__
    super().__init__(config=config, **kw)
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 494, in _init_preprocessors
    conf = self._get_conf()
  File "/Users/guardian/miniconda3/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 512, in _get_conf
    if conf_path.exists():
  File "/Users/guardian/miniconda3/lib/python3.7/pathlib.py", line 1361, in exists
    self.stat()
  File "/Users/guardian/miniconda3/lib/python3.7/pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'
```

**Comment by txoof** [comment]
what are the permissions on the `/usr/local/share/jupyter/nbconvert/templates/` directory?

try: `ls -alh /usr/local/share/jupyter/nbconvert/templates/` and `ls -alh /usr/local/share/jupyter/nbconvert/templates/conf.json`

**Comment by gideonsimpson** [comment]
I got permissions denied on both of them.  What permissions should they have?

**Comment by gideonsimpson** [comment]
Or, alternatively, how can I set things for the user to use a local version?

**Comment by txoof** [comment]
This are the defaults created by the latest version of nbconvert
```
$ dir /usr/local/share/jupyter/nbconvert/templates 
total 0
drwx------  4 aaronciuffo  admin   128B Sep 29 19:56 .
drwxr-xr-x  3 aaronciuffo  admin    96B Sep 25 18:30 ..
drwx------  2 aaronciuffo  admin    64B Sep 29 19:56 html
drwx------  2 aaronciuffo  admin    64B Sep 29 19:56 latex
```
You should have a local copy somewhere in your path. Try `jupyter --paths` it should look something like this.

```
$ jupyter --paths                                                    (master) ✗
config:
    /Users/aaronciuffo/.jupyter
    /Users/aaronciuffo/.pyenv/versions/3.8.5/Python.framework/Versions/3.8/etc/jupyter 
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/aaronciuffo/Library/Jupyter <- local user version
    /Users/aaronciuffo/.pyenv/versions/3.8.5/Python.framework/Versions/3.8/share/jupyter <- local user version
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/aaronciuffo/Library/Jupyter/runtime
```
afaik the local version was created when jupyter was installed by pip.

**Comment by gideonsimpson** [comment]
So the issue might be that I have two accounts on this machine, one that's admin, and the other on which I'm running the jupyter lab server.  On the administrative account I have:
```
config:
    /Users/gideonsimpson/.jupyter
    /Users/gideonsimpson/miniconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/gideonsimpson/Library/Jupyter
    /Users/gideonsimpson/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/gideonsimpson/Library/Jupyter/runtime
```
while on the jupyter account, I have:
```
config:
    /Users/guardian/.jupyter
    /Users/guardian/miniconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/guardian/Library/Jupyter
    /Users/guardian/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/guardian/Library/Jupyter/runtime
```
But, the `guardian` account does not seem to have permissions to the `/usr` stuff:
```
gideonsimpson@machine:~$ ls -l /usr/local/share/jupyter/nbconvert/templates
total 0
drwx------  2 gideonsimpson  admin  64 Sep 16 15:31 html
drwx------  2 gideonsimpson  admin  64 Sep 16 15:31 latex
```
while
```
guardian@machine:~$ ls -l /usr/local/share/jupyter/nbconvert/template
ls: templates: Permission denied
```
I would not to give the `guardian` account root access, but am unsure of how to best handle this situation.

**Comment by txoof** [comment]
I thing the solution is to change the permissions on recursively `/usr/local/share/jupyter/` 0755 and the permissions of the files within the nbconvert folder to 0644.

This feels pretty ugly, but will probably solve your problem.

You can use the find command to do this:
```
# change the permissions on the directories to group, other read and execute
$ find ./ -type d -exec chmod go+rx {} \;

# change all the other files to group, other read
$ find ./ -type f -exec chmod  go+r {} \;

# change all the executables to group, other execute
$ find ./ -type f -perm -100 -exec chmod go+x {} \;
```

**Comment by gideonsimpson** [comment]
Yup, that did it.

**Comment by JunweiSUN** [comment]
Hi @gideonsimpson , I found that if I install jupyterhub and jupyterlab using conda with root, the permission of `/usr/local/share/jupyter/nbconvert/templates` will be 0700, and other users without root will not be able to write `conf.json` into this dir. I think this is because nbconvert was not designed for multi-user initially like jupyterhub. Will there be a plan to add multi-user support for nbconvert?

**Comment by k-nayak** [comment]
> This are the defaults created by the latest version of nbconvert
> 
> ```
> $ dir /usr/local/share/jupyter/nbconvert/templates 
> total 0
> drwx------  4 aaronciuffo  admin   128B Sep 29 19:56 .
> drwxr-xr-x  3 aaronciuffo  admin    96B Sep 25 18:30 ..
> drwx------  2 aaronciuffo  admin    64B Sep 29 19:56 html
> drwx------  2 aaronciuffo  admin    64B Sep 29 19:56 latex
> ```
> 
> You should have a local copy somewhere in your path. Try `jupyter --paths` it should look something like this.
> 
> ```
> $ jupyter --paths                                                    (master) ✗
> config:
>     /Users/aaronciuffo/.jupyter
>     /Users/aaronciuffo/.pyenv/versions/3.8.5/Python.framework/Versions/3.8/etc/jupyter 
>     /usr/local/etc/jupyter
>     /etc/jupyter
> data:
>     /Users/aaronciuffo/Library/Jupyter <- local user version
>     /Users/aaronciuffo/.pyenv/versions/3.8.5/Python.framework/Versions/3.8/share/jupyter <- local user version
>     /usr/local/share/jupyter
>     /usr/share/jupyter
> runtime:
>     /Users/aaronciuffo/Library/Jupyter/runtime
> ```
> 
> afaik the local version was created when jupyter was installed by pip.


I am getting an outpu like this: 
drwx------  2 root root 4.0K Jun 23 11:08 .
drwxrwxrwx 16 root root 4.0K Jun 24 14:37 ..

also not able to create or open any .ipynb files in jupyter notebook and jupyterhub. Both installed on the same linux machine.

Any solution to this error?

**Comment by k-nayak** [comment]
This Permission error is caused due to the version of nbconvert. nbconvert 6.1.0 was the reason for this error. I have downgraded the nbconvert to 5.6.1 and it fixed the issue for me. I no longer face the Permission error any more while trying to open .ipynb files.

**Comment by bklaas** [comment]
I administer jupyterhub/lab for two separate institutions, and this has bit us both places. As @k-nayak helpfully points out, the workaround is to downgrade to 5.6.1 (thanks!), but I would recommend this issue re-open as it's a significant break for multi-user applications of this.

**Comment by jxu** [comment]
I have this problem as well and downgrading worked but is never the best solution

**Comment by jasongrout** [comment]
> This Permission error is caused due to the version of nbconvert. nbconvert 6.1.0 was the reason for this error.

@k-nayak - can you elaborate on this? What do you think 6.1.0 did that was wrong? @jxu, do you have any insights? @bklaas?

We're in the release process for 6.2.0, and if we have some clues as to why 6.1.0 seems to have a problem, but 5.6 does not, it would really help. Is it a permission problem when 6.1.0 is installed, but somehow 5.6 does not have the permission problem? Typically permissions are dealt with by the installer, so it's a bit puzzling.

@SylvainCorlay - did nbconvert 6.0 switch where it put templates, causing some of these permission issues?

**Comment by jasongrout** [comment]
Investigating this, nbconvert 5.6 stores its templates in site-packages:
```
        "lib/python3.9/site-packages/nbconvert/templates/README.md",
        "lib/python3.9/site-packages/nbconvert/templates/asciidoc.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/html/basic.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/html/celltags.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/html/full.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/html/mathjax.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/html/slides_reveal.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/latex/article.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/base.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/document_contents.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/report.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/skeleton/display_priority.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/skeleton/null.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/style_bw_ipython.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/style_bw_python.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/style_ipython.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/style_jupyter.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/latex/style_python.tplx",
        "lib/python3.9/site-packages/nbconvert/templates/markdown.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/python.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/rst.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/script.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/skeleton/README.md",
        "lib/python3.9/site-packages/nbconvert/templates/skeleton/display_priority.tpl",
        "lib/python3.9/site-packages/nbconvert/templates/skeleton/null.tpl",
```
while nbconvert 6.1 stores its templates in the share directory:
```
        "share/jupyter/nbconvert/templates/asciidoc/conf.json",
        "share/jupyter/nbconvert/templates/asciidoc/index.asciidoc.j2",
        "share/jupyter/nbconvert/templates/base/celltags.j2",
        "share/jupyter/nbconvert/templates/base/display_priority.j2",
        "share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2",
        "share/jupyter/nbconvert/templates/base/mathjax.html.j2",
        "share/jupyter/nbconvert/templates/base/null.j2",
        "share/jupyter/nbconvert/templates/basic/conf.json",
        "share/jupyter/nbconvert/templates/basic/index.html.j2",
        "share/jupyter/nbconvert/templates/classic/base.html.j2",
        "share/jupyter/nbconvert/templates/classic/conf.json",
        "share/jupyter/nbconvert/templates/classic/index.html.j2",
        "share/jupyter/nbconvert/templates/classic/static/style.css",
        "share/jupyter/nbconvert/templates/compatibility/display_priority.tpl",
        "share/jupyter/nbconvert/templates/compatibility/full.tpl",
        "share/jupyter/nbconvert/templates/lab/base.html.j2",
        "share/jupyter/nbconvert/templates/lab/conf.json",
        "share/jupyter/nbconvert/templates/lab/index.html.j2",
        "share/jupyter/nbconvert/templates/lab/static/index.css",
        "share/jupyter/nbconvert/templates/lab/static/theme-dark.css",
        "share/jupyter/nbconvert/templates/lab/static/theme-light.css",
        "share/jupyter/nbconvert/templates/latex/base.tex.j2",
        "share/jupyter/nbconvert/templates/latex/conf.json",
        "share/jupyter/nbconvert/templates/latex/display_priority.j2",
        "share/jupyter/nbconvert/templates/latex/document_contents.tex.j2",
        "share/jupyter/nbconvert/templates/latex/index.tex.j2",
        "share/jupyter/nbconvert/templates/latex/null.j2",
        "share/jupyter/nbconvert/templates/latex/report.tex.j2",
        "share/jupyter/nbconvert/templates/latex/style_bw_ipython.tex.j2",
        "share/jupyter/nbconvert/templates/latex/style_bw_python.tex.j2",
        "share/jupyter/nbconvert/templates/latex/style_ipython.tex.j2",
        "share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2",
        "share/jupyter/nbconvert/templates/latex/style_python.tex.j2",
        "share/jupyter/nbconvert/templates/markdown/conf.json",
        "share/jupyter/nbconvert/templates/markdown/index.md.j2",
        "share/jupyter/nbconvert/templates/python/conf.json",
        "share/jupyter/nbconvert/templates/python/index.py.j2",
        "share/jupyter/nbconvert/templates/reveal/base.html.j2",
        "share/jupyter/nbconvert/templates/reveal/conf.json",
        "share/jupyter/nbconvert/templates/reveal/index.html.j2",
        "share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css",
        "share/jupyter/nbconvert/templates/rst/conf.json",
        "share/jupyter/nbconvert/templates/rst/index.rst.j2",
        "share/jupyter/nbconvert/templates/script/conf.json",
        "share/jupyter/nbconvert/templates/script/script.j2",
        "share/jupyter/nbconvert/templates/webpdf/conf.json",
        "share/jupyter/nbconvert/templates/webpdf/index.pdf.j2"
```
Plenty of Jupyter packages store data in the `share/jupyter` directory (e.g., JupyterLab, Jupyter Notebook, IPython kernel spec, etc.). Putting files there is not out of the ordinary at all. The files in that `share/jupyter` directory should be readable to function.

If you install, for example, JupyterLab, Jupyter Notebook, ipywidgets, etc. in the same way, are their `share/jupyter` files also unreadable?

**Comment by jasongrout** [comment]
I just checked, and making those `share/jupyter/nbconvert` files read-only still enables nbconvert to work just fine (from the JupyterLab menu), i.e., nbconvert doesn't seem to try to write to those files. Making those `share/jupyter/nbconvert` files not readable predictably causes problems, leading to errors like shown above and a blank export menu in JupyterLab.

So again, are people that are seeing this issue able to install JupyterLab, ipywidgets, Jupyter Notebook in the same way and see their `share/jupyter` directories readable?

**Comment by SylvainCorlay** [comment]
@jasongrout it seems that the culprit is this snippet:

https://github.com/jupyter/nbconvert/blob/4607ed2078f38a63d055e76307d9f66f32e8a5fd/nbconvert/exporters/templateexporter.py#L550-L555, and more specifically the call to `ensure_dir_exists`

```python
        additional_paths = self.template_data_paths
        for path in additional_paths:
            try:
                ensure_dir_exists(path, mode=0o700)
            except OSError:
                pass
```

It causes the creation of an empty `templates` folder for all levels of `additional_paths` some of which may be system libraries.

**Comment by rvalieris** [comment]
dont know if this helps but I came across this issue on a multi-user shared jupyterhub installation, I think user1 wrote the file, then user2 tried to write the file and failed with permission denied.

I "solved" the issue by re-installing everything and removing write permissions of all users, but I'm not sure if this will break something on nbconvert.

on a multi-user install I would rather not have any user writing files on the install dir, if the file is required by nbconvert it should be installed by the package manager, otherwise write it in a user-specific directory.

**Comment by SylvainCorlay** [comment]
> on a multi-user install I would rather not have any user writing files on the install dir, if the file is required by nbconvert it should be installed by the package manager, otherwise write it in a user-specific directory.

yeah, if the faulty part of the code is the one I mentioned about, we should be able to not have any file or directory created by users.

**Comment by rvalieris** [comment]
> yeah, if the faulty part of the code is the one I mentioned about, we should be able to not have any file or directory created by users.

nice ! I missed that post actually, looks like that could be it. although I think I remember a "conf" file inside the directory, I might be misremembering tho, sorry.

**Comment by jxu** [comment]
I have a pretty messy python environment from years of sometimes using sudo for install, sometimes local user install. I guess it is something weird between running as sudo and normal user.

**Comment by jasongrout** [comment]
> @jasongrout it seems that the culprit is this snippet:

So (reconstructing might be happening) - this is somehow called by root once, which creates these directories with permission 700, and then those directories are not readable by other users?

**Comment by jasongrout** [comment]
That code was introduced in https://github.com/jupyter/nbconvert/pull/1028. When Maarten extended the template paths in https://github.com/jupyter/nbconvert/pull/1056, I think the code was copied, but had some of these unintended consequences.

**Comment by jasongrout** [comment]
After reviewing the two PRs #1028 and #1056, I think we can just remove this code. I've done this in https://github.com/jupyter/nbconvert/pull/1646, ready for review.

**Comment by k-nayak** [comment]
> > This Permission error is caused due to the version of nbconvert. nbconvert 6.1.0 was the reason for this error.
> 
> @k-nayak - can you elaborate on this? What do you think 6.1.0 did that was wrong? @jxu, do you have any insights? @bklaas?
> 
> We're in the release process for 6.2.0, and if we have some clues as to why 6.1.0 seems to have a problem, but 5.6 does not, it would really help. Is it a permission problem when 6.1.0 is installed, but somehow 5.6 does not have the permission problem? Typically permissions are dealt with by the installer, so it's a bit puzzling.
> 
> @SylvainCorlay - did nbconvert 6.0 switch where it put templates, causing some of these permission issues?

Sorry for the late response, i don't think i have an explaination for the issue as it was something i came accross while searching multiple forums.

**Comment by jasongrout** [comment]
We just released 6.2.0rc2, which fixes at least one situation that we think might cause the error (i.e., a situation where we think nbconvert will create directories with restrictive permissions that will give permission errors later when a different user accesses them).

**Comment by teh** [comment]
If there are other people who still hit this with the 6.2 release - in our case this happens when we're converting some notebooks in our CI which runs in a sandbox and can't access `/usr`. We fixed it with the patch below.

```diff
diff --git a/nbconvert/exporters/templateexporter.py b/nbconvert/exporters/templateexporter.py
index a3991b87..47cf59ed 100644
--- a/nbconvert/exporters/templateexporter.py
+++ b/nbconvert/exporters/templateexporter.py
@@ -516,9 +516,12 @@ class TemplateExporter(Exporter):
         conf = {}  # the configuration once all conf files are merged
         for path in map(Path, self.template_paths):
             conf_path = path / 'conf.json'
-            if conf_path.exists():
-                with conf_path.open() as f:
-                    conf = recursive_update(conf, json.load(f))
+            try:
+                if conf_path.exists():
+                    with conf_path.open() as f:
+                        conf = recursive_update(conf, json.load(f))
+            except PermissionError:
+                continue
         return conf
 
     @default('template_paths')
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/500-error-on-loading-notebook/12929/5

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/500-error-on-loading-notebook/12929/6

**Comment by YubinXie** [comment]
In deed, this issue still exists with nbconvert 7.0.0 and 6.4.4. and it is about the permission of /usr/local/share/jupyter/nbconvert/templates/. using sudo to change permission helped.

**Comment by jjlex** [comment]
Looks like it's a problem of pathlib. 
```
>>> from pathlib import Path
>>> p = Path('/share/apps/miniconda/2021.05/share/jupyter/nbconvert/templates/html/conf.json')
>>> p.exists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/apps/miniconda/2021.05/lib/python3.8/pathlib.py", line 1400, in exists
    self.stat()
  File "/share/apps/miniconda/2021.05/lib/python3.8/pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/share/apps/miniconda/2021.05/share/jupyter/nbconvert/templates/html/conf.json'
```

after giving execute permission to the html folder, the problem is resolved
```
chmod +x /share/apps/miniconda/2021.05/share/jupyter/nbconvert/templates/html

>>> p.exists()
False
```
